import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/Navbar";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`container mx-auto p-1 ${geistSans.variable} ${geistMono.variable} antialiased container mx-auto p-4`}
      >
        <header className='bg-gray-50 h-16 mb-4 flex items-center justify-center'>
          <NavBar />
        </header>
        <div className='flex flex-col md:flex-row gap-4'>{children}</div>
        <footer className='bg-gray-50 h-16 mt-4 flex items-center justify-center'>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
